### ISSUE TITLE
Implement Styles for 'Benchmarking' page

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/deep-microservices-benchmarking#4]
- Improve styles for 'start' buttons 
- Improve styles for 'loops' and 'interval' fields 
- Improve styles for 'radio button'

Please refer to attachment for more details 

![improvestylesforbenchmarking](https://cloud.githubusercontent.com/assets/12330493/11743016/fdc0948c-a00c-11e5-81e4-f7e73db713fc.png)

**Comment by mgoria** [comment]
@eistrati This issue seems to be done, Diana has improved this UI, and now it looks as follow:
![screen shot 2016-03-22 at 11 51 03 am](https://cloud.githubusercontent.com/assets/2959952/13947705/af9c2b96-f024-11e5-8a76-4d53d3f56d9e.png)

Are there any other changes / improvements we have to do, or we can close it ?

**Comment by eistrati** [comment]
Yes, we can close it now. Thank you!
